spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 5863856
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
ipfilter:
  timeWindow: 60000
  times: 10
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint: 
    health: 
      show-details: always
